version: '3.7'

services:
  web:
    build: .
    command: python /new/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/new
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_PASSWORD=postgres

volumes: 
  postgres_data: